Global:
  checkpoints: null
  pretrained_model:
  output_dir: /workspace/output
  append_datetime_to_output_dir: False
  device: gpu
  save_interval: 1
  train_mode: sam
  eval_during_train: True
  eval_interval: 1
  epochs: 8
  print_batch_step: 500
  use_visualdl: False
  # used for static mode and model export
  export_dynamic_batch: True
  image_shape: [3, 512, 512]
  student_size: &student_size 512
  teacher_size: &teacher_size 512

# model ema
# EMA:
#   decay: 0.9998

AMP:
  use_amp: True
  use_fp16_test: False
  scale_loss: 128.0
  use_dynamic_loss_scaling: True
  use_promote: False
  # O1: mixed fp16, O2: pure fp16
  level: O1

Arch:
  name: Sam_PPHGNetV2_B2
  pretrained: True
  use_ssld: True
  use_lab: False

Teacher:
  name: TrtModel
  path: /workspace/onnx/efficientvit_prep_image_encoder_bs8.engine

# loss function config for training/eval process
Loss:
  Train:
    - DistanceLoss:
        mode: sqrt_l2 # [l1, l2, smooth_l1]
        weight: 1.0

  Eval:
    - DistanceLoss:
        mode: smooth_l1 # [l1, l2, smooth_l1]
        weight: 1.0

    - DistanceLoss:
        mode: sqrt_l2 # [l1, l2, smooth_l1]
        weight: 1.0

Optimizer:
  name: AdamW
  one_dim_param_no_weight_decay: True
  weight_decay: 0.0001 # 2e-4
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 0.25
    warmup_start_lr: 1e-6
    eta_min: 1e-7

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageFolderDataset
      image_root: /workspace/sa1b
      transform_ops:
        - RandCropImage:
            backend: pil
        - RandFlipImage:
            flip_code: 1
        - SamResizeImage:
            resize_long: 512
            backend: pil
        - SamPad:
            size: 512
            fill_value: 0
    sampler:
      name: DistributedBatchSampler
      batch_size: 8
      drop_last: True
      shuffle: True
    loader:
      num_workers: 8
      use_shared_memory: True
  Eval:
    dataset:
      name: ImageFolderDataset
      image_root: /workspace/val2017
      transform_ops:
        - SamResizeImage:
            resize_long: 512
            backend: pil
        - SamPad:
            size: 512
            fill_value: 0
    sampler:
      name: DistributedBatchSampler
      batch_size: 8
      drop_last: True
      shuffle: False
    loader:
      num_workers: 8
      use_shared_memory: True
